info:
  contact: {}
paths:
  /api/vi/user/register:
    post:
      parameters:
      - description: 手机号码
        in: body
        name: telephone
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 系统错误
          schema:
            type: string
      summary: 用户注册
swagger: "2.0"
