info:
  contact: {}
paths:
  /api/v1/user/register:
    post:
      parameters:
      - description: 姓名
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 用户注册
      tags:
      - User
swagger: "2.0"
